[package]
name = "volt-hard"
version.workspace = true
edition.workspace = true

[dependencies]
volt-core.workspace = true
volt-bus.workspace = true
thiserror.workspace = true

[dev-dependencies]
proptest.workspace = true
